CREATE TYPE "public"."ai_auth_type" AS ENUM('api_key', 'none', 'oauth');--> statement-breakpoint
CREATE TYPE "public"."ai_model_type" AS ENUM('text', 'embedding', 'chat', 'vision');--> statement-breakpoint
CREATE TYPE "public"."ai_provider_type" AS ENUM('cloud', 'local');--> statement-breakpoint
CREATE TYPE "public"."field_transform_type" AS ENUM('none', 'lowercase', 'uppercase', 'trim', 'custom');--> statement-breakpoint
CREATE TYPE "public"."field_type" AS ENUM('text', 'keyword', 'number', 'boolean', 'date', 'datetime', 'url', 'email', 'json', 'array', 'image_url');--> statement-breakpoint
CREATE TYPE "public"."index_status" AS ENUM('creating', 'ready', 'indexing', 'error', 'offline');--> statement-breakpoint
CREATE TYPE "public"."indexing_strategy" AS ENUM('on_upload', 'scheduled', 'manual');--> statement-breakpoint
CREATE TYPE "public"."response_template_role" AS ENUM('search', 'chat');--> statement-breakpoint
CREATE TYPE "public"."search_type" AS ENUM('lexical', 'semantic', 'hybrid');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('user', 'admin', 'moderator');--> statement-breakpoint
CREATE TYPE "public"."vector_similarity" AS ENUM('cosine', 'euclidean', 'dot_product');--> statement-breakpoint
CREATE TABLE "user" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar(64) NOT NULL,
	"password" varchar(64),
	"firstName" varchar(64),
	"lastName" varchar(64),
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"isActive" boolean DEFAULT true,
	"role" "user_role" DEFAULT 'user'
);
--> statement-breakpoint
CREATE TABLE "data_template_fields" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "data_template_fields_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"template_id" bigint NOT NULL,
	"field_name" varchar(255) NOT NULL,
	"field_type" varchar(50) NOT NULL,
	"display_name" varchar(255),
	"is_required" boolean DEFAULT false,
	"is_searchable" boolean DEFAULT true,
	"is_facetable" boolean DEFAULT false,
	"include_in_response" boolean DEFAULT true,
	"boost_value" double precision DEFAULT 1,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"updated_by" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "data_templates" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "data_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" varchar(100) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"icon" varchar(100),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"last_updated_by" varchar(255),
	CONSTRAINT "data_templates_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "response_templates" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "response_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text,
	"data_template_id" bigint NOT NULL,
	"response_template_role" "response_template_role" NOT NULL,
	"template_config" json NOT NULL,
	"visual_settings" json DEFAULT '{}'::json,
	"full_form_config" json NOT NULL,
	"is_active" boolean DEFAULT true,
	"created_by_user_id" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "search_index" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(128) NOT NULL,
	"display_name" varchar(255) NOT NULL,
	"description" text,
	"data_template_id" bigint NOT NULL,
	"search_type" varchar(20) NOT NULL,
	"indexing_strategy" varchar(20) DEFAULT 'on_upload' NOT NULL,
	"number_of_shards" integer DEFAULT 1 NOT NULL,
	"number_of_replicas" integer DEFAULT 0 NOT NULL,
	"refresh_interval" varchar(20) DEFAULT '1s' NOT NULL,
	"language" varchar(20) DEFAULT 'english' NOT NULL,
	"synonyms" json DEFAULT '[]'::json,
	"stop_words" json DEFAULT '[]'::json,
	"analyzer_config" json DEFAULT '{}'::json,
	"ai_provider_id" uuid,
	"ai_model_id" bigint,
	"embedding_dimensions" integer,
	"vector_similarity" varchar(20) DEFAULT 'cosine',
	"rrf_rank_constant" integer DEFAULT 60 NOT NULL,
	"rrf_window_size" integer DEFAULT 100 NOT NULL,
	"status" varchar(20) DEFAULT 'creating' NOT NULL,
	"document_count" integer DEFAULT 0 NOT NULL,
	"index_size_bytes" bigint DEFAULT 0,
	"last_indexed_at" timestamp,
	"mapping_version" integer DEFAULT 1 NOT NULL,
	"last_mapping_synced_at" timestamp,
	"requires_reindex" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_by" uuid,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"updated_by" uuid,
	CONSTRAINT "search_index_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "search_index_fields" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "search_index_fields_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"search_index_id" uuid NOT NULL,
	"field_name" varchar(255) NOT NULL,
	"field_type" varchar(50) NOT NULL,
	"display_name" varchar(255),
	"original_template_field_id" bigint,
	"is_system_field" boolean DEFAULT false NOT NULL,
	"is_required" boolean DEFAULT false NOT NULL,
	"is_searchable" boolean DEFAULT true NOT NULL,
	"is_facetable" boolean DEFAULT false NOT NULL,
	"include_in_response" boolean DEFAULT true NOT NULL,
	"boost_value" double precision DEFAULT 1 NOT NULL,
	"source_field_name" varchar(255),
	"source_field_path" varchar(500),
	"is_mapped" boolean DEFAULT false NOT NULL,
	"is_indexed" boolean DEFAULT true NOT NULL,
	"is_vector_source" boolean DEFAULT false NOT NULL,
	"custom_analyzer" varchar(50),
	"transform_config" json DEFAULT '{"type":"none"}'::json,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "unique_sif_field_per_index" UNIQUE("search_index_id","field_name"),
	CONSTRAINT "unique_sif_source_mapping" UNIQUE("search_index_id","source_field_name")
);
--> statement-breakpoint
CREATE TABLE "chat" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"createdAt" timestamp NOT NULL,
	"messages" json NOT NULL,
	"userId" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chat_configuration_response_templates" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat_configuration_response_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"chat_configuration_id" uuid NOT NULL,
	"response_template_id" bigint NOT NULL,
	"is_default" boolean DEFAULT false,
	"priority" integer DEFAULT 0,
	"description" text,
	"usage_conditions" json,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chat_configurations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_by_user_id" uuid NOT NULL,
	"friendly_name" text NOT NULL,
	"search_index_id" uuid NOT NULL,
	"ai_provider_id" text,
	"ai_model_id" text,
	"system_prompt" text,
	"welcome_message" text,
	"avatar_url" text,
	"brand_color" text,
	"is_active" boolean DEFAULT true,
	"widget_token" uuid DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "chat_configurations_widget_token_unique" UNIQUE("widget_token")
);
--> statement-breakpoint
CREATE TABLE "seed_registry" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "seed_registry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"seed_type" varchar(50) NOT NULL,
	"seed_key" varchar(100) NOT NULL,
	"checksum" varchar(64) NOT NULL,
	"metadata" text,
	"seeded_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai_provider_models" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai_provider_models_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"provider_id" uuid NOT NULL,
	"model_key" varchar(100) NOT NULL,
	"display_name" varchar(150) NOT NULL,
	"description" text,
	"model_type" "ai_model_type" NOT NULL,
	"dimensions" integer,
	"capabilities" json DEFAULT '{}'::json,
	"is_available" boolean DEFAULT true NOT NULL,
	"is_discovered" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "ai_provider_models_provider_model_key" UNIQUE("provider_id","model_key")
);
--> statement-breakpoint
CREATE TABLE "ai_providers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"provider_key" varchar(50) NOT NULL,
	"display_name" varchar(100) NOT NULL,
	"description" text,
	"provider_type" "ai_provider_type" NOT NULL,
	"auth_type" "ai_auth_type" NOT NULL,
	"base_url" varchar(500) NOT NULL,
	"api_key" varchar(500),
	"is_enabled" boolean DEFAULT true NOT NULL,
	"settings" json DEFAULT '{}'::json,
	"last_connection_check" timestamp,
	"last_connection_status" varchar(100),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "ai_providers_provider_key_unique" UNIQUE("provider_key")
);
--> statement-breakpoint
CREATE TABLE "system_defaults" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "system_defaults_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"default_text_provider_id" uuid,
	"default_text_model_id" bigint,
	"default_embedding_provider_id" uuid,
	"default_embedding_model_id" bigint,
	"default_chat_provider_id" uuid,
	"default_chat_model_id" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "data_template_fields" ADD CONSTRAINT "data_template_fields_template_id_data_templates_id_fk" FOREIGN KEY ("template_id") REFERENCES "public"."data_templates"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_index" ADD CONSTRAINT "search_index_data_template_id_data_templates_id_fk" FOREIGN KEY ("data_template_id") REFERENCES "public"."data_templates"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_index" ADD CONSTRAINT "search_index_ai_provider_id_ai_providers_id_fk" FOREIGN KEY ("ai_provider_id") REFERENCES "public"."ai_providers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_index" ADD CONSTRAINT "search_index_ai_model_id_ai_provider_models_id_fk" FOREIGN KEY ("ai_model_id") REFERENCES "public"."ai_provider_models"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_index_fields" ADD CONSTRAINT "search_index_fields_search_index_id_search_index_id_fk" FOREIGN KEY ("search_index_id") REFERENCES "public"."search_index"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_index_fields" ADD CONSTRAINT "search_index_fields_original_template_field_id_data_template_fields_id_fk" FOREIGN KEY ("original_template_field_id") REFERENCES "public"."data_template_fields"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_provider_models" ADD CONSTRAINT "ai_provider_models_provider_id_ai_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."ai_providers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_defaults" ADD CONSTRAINT "system_defaults_default_text_provider_id_ai_providers_id_fk" FOREIGN KEY ("default_text_provider_id") REFERENCES "public"."ai_providers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_defaults" ADD CONSTRAINT "system_defaults_default_text_model_id_ai_provider_models_id_fk" FOREIGN KEY ("default_text_model_id") REFERENCES "public"."ai_provider_models"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_defaults" ADD CONSTRAINT "system_defaults_default_embedding_provider_id_ai_providers_id_fk" FOREIGN KEY ("default_embedding_provider_id") REFERENCES "public"."ai_providers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_defaults" ADD CONSTRAINT "system_defaults_default_embedding_model_id_ai_provider_models_id_fk" FOREIGN KEY ("default_embedding_model_id") REFERENCES "public"."ai_provider_models"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_defaults" ADD CONSTRAINT "system_defaults_default_chat_provider_id_ai_providers_id_fk" FOREIGN KEY ("default_chat_provider_id") REFERENCES "public"."ai_providers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_defaults" ADD CONSTRAINT "system_defaults_default_chat_model_id_ai_provider_models_id_fk" FOREIGN KEY ("default_chat_model_id") REFERENCES "public"."ai_provider_models"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "data_template_fields_template_id_idx" ON "data_template_fields" USING btree ("template_id");--> statement-breakpoint
CREATE INDEX "data_template_fields_template_id_searchable_idx" ON "data_template_fields" USING btree ("template_id","is_searchable");--> statement-breakpoint
CREATE INDEX "data_template_fields_template_id_facetable_idx" ON "data_template_fields" USING btree ("template_id","is_facetable");--> statement-breakpoint
CREATE INDEX "data_template_fields_field_name_idx" ON "data_template_fields" USING btree ("field_name");--> statement-breakpoint
CREATE INDEX "data_template_fields_field_type_idx" ON "data_template_fields" USING btree ("field_type");--> statement-breakpoint
CREATE INDEX "data_templates_slug_idx" ON "data_templates" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "data_templates_name_idx" ON "data_templates" USING btree ("name");--> statement-breakpoint
CREATE INDEX "data_templates_created_at_idx" ON "data_templates" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "search_index_name_idx" ON "search_index" USING btree ("name");--> statement-breakpoint
CREATE INDEX "search_index_data_template_id_idx" ON "search_index" USING btree ("data_template_id");--> statement-breakpoint
CREATE INDEX "search_index_search_type_idx" ON "search_index" USING btree ("search_type");--> statement-breakpoint
CREATE INDEX "search_index_status_idx" ON "search_index" USING btree ("status");--> statement-breakpoint
CREATE INDEX "search_index_is_active_idx" ON "search_index" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_sif_search_index_id" ON "search_index_fields" USING btree ("search_index_id");--> statement-breakpoint
CREATE INDEX "idx_sif_field_name" ON "search_index_fields" USING btree ("search_index_id","field_name");--> statement-breakpoint
CREATE INDEX "idx_sif_is_mapped" ON "search_index_fields" USING btree ("search_index_id","is_mapped");--> statement-breakpoint
CREATE INDEX "idx_sif_is_system_field" ON "search_index_fields" USING btree ("search_index_id","is_system_field");--> statement-breakpoint
CREATE INDEX "idx_sif_template_field_ref" ON "search_index_fields" USING btree ("original_template_field_id");--> statement-breakpoint
CREATE INDEX "chat_user_id_idx" ON "chat" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "chat_created_at_idx" ON "chat" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "chat_config_response_templates_chat_config_id_idx" ON "chat_configuration_response_templates" USING btree ("chat_configuration_id");--> statement-breakpoint
CREATE INDEX "chat_config_response_templates_response_template_id_idx" ON "chat_configuration_response_templates" USING btree ("response_template_id");--> statement-breakpoint
CREATE INDEX "chat_config_response_templates_is_default_idx" ON "chat_configuration_response_templates" USING btree ("is_default");--> statement-breakpoint
CREATE INDEX "chat_configurations_created_by_user_id_idx" ON "chat_configurations" USING btree ("created_by_user_id");--> statement-breakpoint
CREATE INDEX "chat_configurations_search_index_id_idx" ON "chat_configurations" USING btree ("search_index_id");--> statement-breakpoint
CREATE INDEX "chat_configurations_widget_token_idx" ON "chat_configurations" USING btree ("widget_token");--> statement-breakpoint
CREATE INDEX "chat_configurations_is_active_idx" ON "chat_configurations" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "seed_registry_type_key_idx" ON "seed_registry" USING btree ("seed_type","seed_key");--> statement-breakpoint
CREATE INDEX "seed_registry_type_idx" ON "seed_registry" USING btree ("seed_type");--> statement-breakpoint
CREATE INDEX "ai_provider_models_provider_id_idx" ON "ai_provider_models" USING btree ("provider_id");--> statement-breakpoint
CREATE INDEX "ai_provider_models_model_type_idx" ON "ai_provider_models" USING btree ("model_type");--> statement-breakpoint
CREATE INDEX "ai_provider_models_is_available_idx" ON "ai_provider_models" USING btree ("is_available");--> statement-breakpoint
CREATE INDEX "ai_providers_provider_key_idx" ON "ai_providers" USING btree ("provider_key");--> statement-breakpoint
CREATE INDEX "ai_providers_is_enabled_idx" ON "ai_providers" USING btree ("is_enabled");