// @ts-check
// Minimal Docusaurus config for the public docs site.
//
// The Markdown source of truth stays at backend/src/content/docs (also served
// in-app). The Pages workflow copies it into docs-site/docs before building, so
// this config renders that folder as a docs-only site at the Pages root.

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Interakt Docs',
  tagline: 'AI-powered search & chat platform',
  url: 'https://docs.interakt.app',
  // Served at the root of the custom domain, so baseUrl is '/'.
  // (Was '/interakt/' for project Pages under alphasolutionsrepo.github.io.)
  baseUrl: '/',
  organizationName: 'alphasolutionsrepo',
  projectName: 'interakt',

  // Don't fail the build on a stray relative link in the authored docs.
  onBrokenLinks: 'warn',

  markdown: {
    // Force CommonMark for ALL Markdown (not MDX), so plain-Markdown constructs in
    // the authored docs — literal <angle> placeholders, { braces }, etc. — are
    // treated as text and never break the build. ('detect' still MDX-parses files
    // that look MDX-ish, which these aren't.)
    format: 'md',
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          path: 'docs',
          // Serve docs at the site root (docs-only site).
          routeBasePath: '/',
          sidebarPath: require.resolve('./sidebars.js'),
          // Required by docusaurus-theme-openapi-docs to render API reference pages.
          docItemComponent: '@theme/ApiItem',
        },
        blog: false,
        pages: false,
        theme: {},
      }),
    ],
  ],

  // API reference is generated from the public OpenAPI spec by
  // docusaurus-plugin-openapi-docs into docs/api/ (a build artifact — the docs/
  // folder is git-ignored and re-staged each build). Run `npm run gen-api-docs`
  // before `build`; the autogenerated sidebar then includes the API section.
  plugins: [
    // Webpack fixes the openapi theme needs:
    //  1. Its "Try it" code-sample generator (postman-code-generators) imports
    //     Node's `path`, which webpack 5 no longer polyfills automatically.
    //  2. The theme ships CommonJS (no package "type") but the dev server
    //     evaluates some files as ESM, throwing "exports is not defined" at
    //     runtime. Forcing `javascript/auto` lets webpack detect CJS correctly.
    //     (The production build already wraps them as CJS, so this is dev-only.)
    () => ({
      name: 'openapi-webpack-compat',
      configureWebpack: () => ({
        resolve: { fallback: { path: require.resolve('path-browserify') } },
        module: {
          rules: [
            {
              test: /[\\/]docusaurus-theme-openapi-docs[\\/]lib[\\/].*\.js$/,
              type: 'javascript/auto',
            },
          ],
        },
      }),
    }),
    [
      'docusaurus-plugin-openapi-docs',
      {
        id: 'openapi',
        docsPluginId: 'classic',
        config: {
          interakt: {
            specPath: 'static/openapi/interakt-v1.yaml',
            outputDir: 'docs/api',
            downloadUrl: '/openapi/interakt-v1.yaml',
            sidebarOptions: { groupPathsBy: 'tag', categoryLinkSource: 'tag' },
          },
        },
      },
    ],
  ],

  themes: ['docusaurus-theme-openapi-docs'],

  themeConfig: /** @type {import('@docusaurus/preset-classic').ThemeConfig} */ ({
    navbar: {
      title: 'Interakt',
      items: [
        { to: '/api/interakt-public-api', label: 'API Reference', position: 'left' },
      ],
    },
    colorMode: { respectPrefersColorScheme: true },
  }),
};

module.exports = config;
