// Auto-generate the sidebar from the docs folder structure. This honors the
// `sidebar_position` frontmatter the Markdown already uses, so nav order +
// folder→section hierarchy match the in-app docs.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};
