// db/schema/ai-sessions.schema.ts

/**
 * AI Session Schema — Unified Sessions for All AI Experiences
 *
 * Split-table design for tiered memory:
 *
 * Tier 1 (hot)  — `ai_sessions` row: summary, facts, pipelineState, lastToolResults
 *                 + last N messages from `ai_session_messages` (loaded every turn)
 * Tier 2 (warm) — `ai_session_messages`: full history, queryable via memory retrieval tool
 * Tier 3 (cold) — Phase 3: cross-session user memory, archival
 *
 * The session row is lean and loaded on every turn. Messages are in a separate
 * table so the session row never grows unbounded.
 */

import {
  pgTable,
  uuid,
  text,
  json,
  timestamp,
  integer,
  index,
  vector,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import { aiExperiences } from './ai-experience.schema';
import { sessionMessageRoleEnum, sessionStatusEnum } from './enums.schema';

// ============================================================================
// TYPE DEFINITIONS FOR JSON COLUMNS
// ============================================================================

/**
 * Extracted facts from conversation — structured key-value pairs
 * populated during summarization and tool result extraction.
 * Examples: { "budget": "$50", "intent": "compare", "preferred_brand": "Nike" }
 */
export type SessionFacts = Record<string, unknown>;

/**
 * Per-step namespaced pipeline state.
 * Each step handler reads/writes its own namespace.
 * Example: { "intent_detection": { "lastIntent": "search" }, "constraint_extraction": { "filters": [...] } }
 */
export type PipelineState = Record<string, Record<string, unknown>>;

/**
 * User context for identity-aware sessions (Phase 3 ready).
 * Schema is defined now but population is Phase 3.
 */
export interface SessionUserContext {
  /** External user identifier */
  userId?: string;
  /** Display name */
  displayName?: string;
  /** User-level preferences */
  preferences?: Record<string, unknown>;
  /** Permissions / roles */
  permissions?: string[];
}

/**
 * Last tool results — updated after every tool execution.
 * Survives window rotation so AI can reference recent tool output
 * even if the original message has scrolled out of the window.
 * Keyed by tool type or tool ID for multi-tool support.
 */
export type LastToolResults = Record<string, {
  toolId: string;
  toolName: string;
  result: unknown;
  executedAt: string;
}>;

/**
 * Message metadata — attached to each message for tracing and rich rendering.
 */
export interface SessionMessageMetadata {
  /** Tool calls made during this turn */
  toolCalls?: Array<{
    toolId: string;
    toolName: string;
    input: unknown;
    durationMs?: number;
  }>;
  /** Token usage for LLM calls */
  tokenUsage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
  /** Latency in ms for this message generation */
  latencyMs?: number;
  /** Pipeline step trace for this turn */
  stepTrace?: Array<{
    stepId: string;
    stepType: string;
    durationMs: number;
    status: 'success' | 'skipped' | 'error';
  }>;
  /** Rich response data for re-rendering (preset, structured content) */
  responseData?: {
    preset: string;
    content: unknown;
  };
}

// ============================================================================
// AI SESSIONS TABLE (lean — loaded every turn)
// ============================================================================

export const aiSessions = pgTable('ai_sessions', {
  id: uuid('id').primaryKey().defaultRandom(),

  /** Reference to the AI experience this session belongs to */
  aiExperienceId: uuid('ai_experience_id')
    .notNull()
    .references(() => aiExperiences.id, { onDelete: 'cascade' }),

  // ═══════════════════════════════════════════════════════════════════════════
  // TIER 1: WORKING MEMORY (loaded into LLM context every turn)
  // ═══════════════════════════════════════════════════════════════════════════

  /** Compressed summary of older messages (generated by summarization service) */
  summary: text('summary'),

  /** Extracted facts from conversation — structured key-value pairs */
  facts: json('facts').$type<SessionFacts>().default({}),

  /** Per-step namespaced pipeline state (deterministic pipeline uses heavily) */
  pipelineState: json('pipeline_state').$type<PipelineState>().default({}),

  /** Last tool results — always-fresh, survives window rotation */
  lastToolResults: json('last_tool_results').$type<LastToolResults>().default({}),

  // ═══════════════════════════════════════════════════════════════════════════
  // USER CONTEXT (Phase 3 ready)
  // ═══════════════════════════════════════════════════════════════════════════

  /** Optional user identity and preferences */
  userContext: json('user_context').$type<SessionUserContext>(),

  // ═══════════════════════════════════════════════════════════════════════════
  // METADATA
  // ═══════════════════════════════════════════════════════════════════════════

  /** Session status */
  status: sessionStatusEnum('status').notNull().default('active'),

  /** Total messages in the session (across all turns) */
  messageCount: integer('message_count').default(0).notNull(),

  /** Number of messages covered by the current summary */
  summarizedUpTo: integer('summarized_up_to').default(0).notNull(),

  /** Optional client-provided metadata (device info, page context, etc.) */
  clientMetadata: json('client_metadata').$type<Record<string, unknown>>(),

  // ═══════════════════════════════════════════════════════════════════════════
  // TIMESTAMPS
  // ═══════════════════════════════════════════════════════════════════════════
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  lastActiveAt: timestamp('last_active_at', { withTimezone: true }).defaultNow().notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),

}, (table) => ({
  experienceIdx: index('ai_sessions_experience_idx').on(table.aiExperienceId),
  statusIdx: index('ai_sessions_status_idx').on(table.status),
  lastActiveIdx: index('ai_sessions_last_active_idx').on(table.lastActiveAt),
  expiresAtIdx: index('ai_sessions_expires_at_idx').on(table.expiresAt),
  // Composite: find active sessions for an experience
  experienceStatusIdx: index('ai_sessions_experience_status_idx').on(table.aiExperienceId, table.status),
}));

// ============================================================================
// AI SESSION MESSAGES TABLE (separate, queryable, archivable)
// ============================================================================

export const aiSessionMessages = pgTable('ai_session_messages', {
  id: uuid('id').primaryKey().defaultRandom(),

  /** Reference to the session */
  sessionId: uuid('session_id')
    .notNull()
    .references(() => aiSessions.id, { onDelete: 'cascade' }),

  /** Message role */
  role: sessionMessageRoleEnum('role').notNull(),

  /** Message content (text for user/assistant/system, JSON string for tool_result) */
  content: text('content').notNull(),

  /** Sequential turn number within the session (0-based) */
  turnIndex: integer('turn_index').notNull(),

  /** Rich metadata: tool calls, token usage, latency, step trace */
  metadata: json('metadata').$type<SessionMessageMetadata>(),

  /** When this message was created */
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),

  /**
   * Embedding vector for semantic search (pgvector).
   * Generated async after message insertion via the embedding service.
   * NULL until embedded (or if embedding fails/is disabled).
   * Dimension 1536 matches OpenAI text-embedding-3-small / ada-002.
   */
  embedding: vector('embedding', { dimensions: 1536 }),

}, (table) => ({
  sessionIdx: index('ai_session_messages_session_idx').on(table.sessionId),
  // Composite for sliding window: load last N by session + turnIndex desc
  sessionTurnIdx: index('ai_session_messages_session_turn_idx').on(table.sessionId, table.turnIndex),
  // For memory retrieval tool: search by session + role
  sessionRoleIdx: index('ai_session_messages_session_role_idx').on(table.sessionId, table.role),
  // For cleanup/archival: find old messages
  createdAtIdx: index('ai_session_messages_created_at_idx').on(table.createdAt),
  // pgvector HNSW index for cosine similarity search (memory retrieval)
  embeddingIdx: index('ai_session_messages_embedding_idx').using('hnsw', table.embedding.op('vector_cosine_ops')),
}));

// ============================================================================
// RELATIONS
// ============================================================================

export const aiSessionsRelations = relations(aiSessions, ({ one, many }) => ({
  aiExperience: one(aiExperiences, {
    fields: [aiSessions.aiExperienceId],
    references: [aiExperiences.id],
  }),
  messages: many(aiSessionMessages),
}));

export const aiSessionMessagesRelations = relations(aiSessionMessages, ({ one }) => ({
  session: one(aiSessions, {
    fields: [aiSessionMessages.sessionId],
    references: [aiSessions.id],
  }),
}));

// ============================================================================
// TYPE EXPORTS
// ============================================================================

export type AISession = typeof aiSessions.$inferSelect;
export type NewAISession = typeof aiSessions.$inferInsert;

export type AISessionMessage = typeof aiSessionMessages.$inferSelect;
export type NewAISessionMessage = typeof aiSessionMessages.$inferInsert;
