// db/analytics-schema/analytics-insights.schema.ts

/**
 * ANALYTICS INSIGHTS SCHEMA
 * ------------------------------------------------------------------------
 * Stores pre-computed analytics insights generated by the processing
 * pipeline. These are read by analytics AI chat tools for fast,
 * business-focused responses.
 *
 * DATABASE: Analytics DB (separate from main app DB)
 * CONFIG: drizzle.analytics.config.ts
 * ------------------------------------------------------------------------
 */

import {
  pgTable,
  varchar,
  timestamp,
  jsonb,
  uuid,
  integer,
  text,
  index,
  unique,
} from 'drizzle-orm/pg-core';
import { InferSelectModel, InferInsertModel } from 'drizzle-orm';

// ============================================================================
// INSIGHT TYPES
// ============================================================================

export type InsightType =
  | 'intent_clusters'
  | 'demand_signals'
  | 'catalog_health'
  | 'ai_effectiveness'
  | 'proactive_insights'
  | 'guardrail_analytics'
  | 'cost_analysis';

export type InsightTimeRange = '24h' | '7d' | '30d';

// ============================================================================
// ANALYTICS INSIGHTS TABLE
// ============================================================================

/**
 * Pre-computed analytics insights
 *
 * Each row stores one insight type for one time range (and optionally one experience).
 * Upserted by the processing pipeline on each run.
 */
export const analyticsInsights = pgTable(
  'analytics_insights',
  {
    id: uuid('id').primaryKey().notNull().defaultRandom(),

    // Scope
    experienceId: uuid('experience_id'), // null = global (all experiences)

    // Insight classification
    insightType: varchar('insight_type', { length: 30 }).notNull(),
    timeRange: varchar('time_range', { length: 10 }).notNull(),

    // Pre-computed result (structure varies by insightType)
    data: jsonb('data').$type<Record<string, unknown>>().notNull().default({}),

    // Processing metadata
    spansProcessed: integer('spans_processed').notNull().default(0),
    processedAt: timestamp('processed_at', { withTimezone: true }).notNull().defaultNow(),
    processingDurationMs: integer('processing_duration_ms').notNull().default(0),
  },
  (table) => [
    // Fast lookup by type + range (primary query pattern for AI tools)
    index('idx_insights_type_range').on(table.insightType, table.timeRange),
    // Scoped queries
    index('idx_insights_experience').on(table.experienceId),
    // Staleness checks
    index('idx_insights_processed_at').on(table.processedAt),
    // Upsert constraint: one row per (experienceId, insightType, timeRange)
    unique('uq_insights_scope').on(table.experienceId, table.insightType, table.timeRange),
  ]
);

export type AnalyticsInsight = InferSelectModel<typeof analyticsInsights>;
export type NewAnalyticsInsight = InferInsertModel<typeof analyticsInsights>;

// ============================================================================
// ANALYTICS PROCESSING RUNS TABLE
// ============================================================================

export type ProcessingRunStatus = 'running' | 'completed' | 'failed';

export interface ProcessingStep {
  step: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  count?: number;
  durationMs?: number;
  error?: string;
}

/**
 * Processing run history
 *
 * Tracks each invocation of the analytics processing pipeline.
 * Used for status polling, staleness detection, and debugging.
 */
export const analyticsProcessingRuns = pgTable(
  'analytics_processing_runs',
  {
    id: uuid('id').primaryKey().notNull().defaultRandom(),

    // Run state
    status: varchar('status', { length: 20 }).notNull().default('running'),

    // Timing
    startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp('completed_at', { withTimezone: true }),

    // Scope
    experienceId: uuid('experience_id'), // null = global
    timeRanges: jsonb('time_ranges').$type<string[]>().notNull().default([]),

    // Progress tracking
    steps: jsonb('steps').$type<ProcessingStep[]>().notNull().default([]),

    // Outcome
    error: text('error'),
    triggeredBy: varchar('triggered_by', { length: 255 }),
  },
  (table) => [
    // Latest run lookup
    index('idx_processing_runs_started').on(table.startedAt),
    // Status filtering
    index('idx_processing_runs_status').on(table.status),
  ]
);

export type AnalyticsProcessingRun = InferSelectModel<typeof analyticsProcessingRuns>;
export type NewAnalyticsProcessingRun = InferInsertModel<typeof analyticsProcessingRuns>;
